using System.Collections.Immutable;
using System.Diagnostics;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace RoslynMcp;

[DebuggerDisplay("{ToString(),nq}")]
internal sealed record DocumentEntry(
    DocumentId Id,
    string Name,
    string? FilePath,
    string Source,
    SyntaxTree Tree,
    SemanticModel Model,
    bool IsSynthetic = false)
{
    public override string ToString() =>
        $"DocumentEntry({Name}, lines={Tree.GetText().Lines.Count}, synthetic={IsSynthetic}, path={FilePath ?? "in-memory"})";
}

[DebuggerDisplay("{ToString(),nq}")]
internal sealed record ResolvedTarget(
    DocumentEntry Document,
    SyntaxNode Node,
    ISymbol? Symbol,
    int Position,
    int Line,
    int Column)
{
    public override string ToString() =>
        $"ResolvedTarget({Document.Name}@L{Line}:{Column} [pos={Position}], node={Node.Kind()}, symbol={Symbol?.MinDisplay() ?? "none"})";
}

[DebuggerDisplay("{ToString(),nq}")]
internal sealed record SourceLocationInfo(
    string File,
    string? FullPath,
    int StartLine,
    int StartColumn,
    int EndLine,
    int EndColumn,
    int SpanStart,
    int SpanLength,
    string LineText)
{
    public override string ToString() => $"{File}:L{StartLine}:{StartColumn}-L{EndLine}:{EndColumn} ({LineText})";
}

[DebuggerDisplay("{ToString(),nq}")]
internal sealed class WorkspaceContext : IDisposable
{
    public AdhocWorkspace Workspace { get; }
    public Solution Solution { get; set; }
    public Project PrimaryProject { get; }
    public CSharpCompilation Compilation { get; }
    public IReadOnlyList<DocumentEntry> Documents { get; }
    public bool IsFromDisk { get; }
    public string? RootPath { get; }

    public WorkspaceContext(
        AdhocWorkspace workspace,
        Solution solution,
        Project primaryProject,
        CSharpCompilation compilation,
        IReadOnlyList<DocumentEntry> documents,
        bool isFromDisk,
        string? rootPath)
    {
        Workspace = workspace;
        Solution = solution;
        PrimaryProject = primaryProject;
        Compilation = compilation;
        Documents = documents;
        IsFromDisk = isFromDisk;
        RootPath = rootPath;
    }

    public IEnumerable<DocumentEntry> UserDocuments => Documents.Where(d => !d.IsSynthetic);

    public DocumentEntry PrimaryDocument =>
        UserDocuments.FirstOrDefault() ?? Documents.First();

    public DocumentEntry? FindDocument(string nameOrPath)
    {
        var normalized = nameOrPath.Replace('\\', '/').Trim();
        return UserDocuments.FirstOrDefault(d =>
            string.Equals(d.Name, normalized, StringComparison.OrdinalIgnoreCase) ||
            string.Equals(d.FilePath?.Replace('\\', '/'), normalized, StringComparison.OrdinalIgnoreCase) ||
            (d.FilePath is not null && d.FilePath.Replace('\\', '/').EndsWith("/" + normalized, StringComparison.OrdinalIgnoreCase)) ||
            d.Name.EndsWith(normalized, StringComparison.OrdinalIgnoreCase));
    }

    public void Dispose() => Workspace.Dispose();

    public override string ToString() =>
        $"WorkspaceContext({PrimaryProject.Name}, docs={UserDocuments.Count()}, fromDisk={IsFromDisk}, root={RootPath ?? "in-memory"})";
}

internal static class WorkspaceEngine
{
    private static readonly Lazy<ImmutableArray<MetadataReference>> LazyDefaultReferences = new(LoadDefaultReferences);

    public static ImmutableArray<MetadataReference> DefaultReferences => LazyDefaultReferences.Value;

    private const string ImplicitGlobalUsingsSource = """
        // <auto-generated/>
        global using global::System;
        global using global::System.Collections.Generic;
        global using global::System.IO;
        global using global::System.Linq;
        global using global::System.Net.Http;
        global using global::System.Text;
        global using global::System.Threading;
        global using global::System.Threading.Tasks;
        """;

    private static ImmutableArray<MetadataReference> LoadDefaultReferences()
    {
        var paths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        if (AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") is string tpa && !string.IsNullOrWhiteSpace(tpa))
        {
            foreach (var p in tpa.Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries))
            {
                if (File.Exists(p) && p.EndsWith(".dll", StringComparison.OrdinalIgnoreCase))
                    paths.Add(p);
            }
        }

        Type[] anchorTypes =
        [
            typeof(object), typeof(Console), typeof(Enumerable), typeof(List<>),
            typeof(Task), typeof(JsonSerializer), typeof(Regex), typeof(XDocument),
            typeof(SyntaxNode), typeof(CSharpSyntaxTree), typeof(AdhocWorkspace)
        ];

        foreach (var t in anchorTypes)
        {
            if (!string.IsNullOrWhiteSpace(t.Assembly.Location) && File.Exists(t.Assembly.Location))
                paths.Add(t.Assembly.Location);
        }

        foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
        {
            if (asm.IsDynamic) continue;
            try
            {
                if (!string.IsNullOrWhiteSpace(asm.Location) && File.Exists(asm.Location))
                    paths.Add(asm.Location);
            }
            catch { }
        }

        var builder = ImmutableArray.CreateBuilder<MetadataReference>(paths.Count);
        foreach (var p in paths.OrderBy(x => x, StringComparer.OrdinalIgnoreCase))
        {
            try { builder.Add(MetadataReference.CreateFromFile(p)); }
            catch { }
        }
        return builder.ToImmutable();
    }

    public static string Serialize(object value) => RoslynHelpers.Ser(value);

    public static WorkspaceContext Load(
        string sourceOrPath,
        string? additionalSourcesJson = null,
        bool includeSiblingFiles = true)
    {
        if (string.IsNullOrWhiteSpace(sourceOrPath))
            throw new ArgumentException("sourceOrPath cannot be empty", nameof(sourceOrPath));

        var fileMap = new List<(string Name, string? FilePath, string Source, bool IsSynthetic)>();
        bool isFromDisk = false;
        string? rootPath = null;
        string projectName = "RoslynWorkspace";

        var trimmed = sourceOrPath.Trim();

        if (trimmed.StartsWith('{') && trimmed.EndsWith('}') && TryParseSourceDictionary(trimmed, out var jsonFiles))
        {
            foreach (var kv in jsonFiles)
                fileMap.Add((kv.Key, null, kv.Value, false));
        }
        else if (LooksLikeDiskPath(trimmed, out var resolvedPath))
        {
            isFromDisk = true;
            rootPath = resolvedPath;

            if (Directory.Exists(resolvedPath))
            {
                projectName = new DirectoryInfo(resolvedPath).Name;
                foreach (var csFile in EnumerateCSharpFiles(resolvedPath))
                    fileMap.Add((Path.GetRelativePath(resolvedPath, csFile).Replace('\\', '/'), csFile, File.ReadAllText(csFile), false));
            }
            else if (File.Exists(resolvedPath))
            {
                var ext = Path.GetExtension(resolvedPath).ToLowerInvariant();
                if (ext == ".csproj")
                {
                    projectName = Path.GetFileNameWithoutExtension(resolvedPath);
                    rootPath = Path.GetDirectoryName(resolvedPath)!;
                    LoadFromCsproj(resolvedPath, rootPath, fileMap);
                }
                else if (ext is ".sln" or ".slnx")
                {
                    projectName = Path.GetFileNameWithoutExtension(resolvedPath);
                    rootPath = Path.GetDirectoryName(resolvedPath)!;
                    LoadFromSolutionFile(resolvedPath, rootPath, fileMap);
                }
                else
                {
                    var fileDir = Path.GetDirectoryName(resolvedPath)!;
                    projectName = Path.GetFileNameWithoutExtension(resolvedPath);
                    fileMap.Add((Path.GetFileName(resolvedPath), resolvedPath, File.ReadAllText(resolvedPath), false));

                    if (includeSiblingFiles)
                    {
                        var enclosingRoot = FindEnclosingProjectDirectory(fileDir) ?? fileDir;
                        rootPath = enclosingRoot;
                        foreach (var sibling in EnumerateCSharpFiles(enclosingRoot))
                        {
                            if (!string.Equals(Path.GetFullPath(sibling), Path.GetFullPath(resolvedPath), StringComparison.OrdinalIgnoreCase))
                                fileMap.Add((Path.GetRelativePath(enclosingRoot, sibling).Replace('\\', '/'), sibling, File.ReadAllText(sibling), false));
                        }
                    }
                }
            }
        }
        else
        {
            fileMap.Add(("Source.cs", null, sourceOrPath, false));
        }

        if (!string.IsNullOrWhiteSpace(additionalSourcesJson) &&
            TryParseSourceDictionary(additionalSourcesJson.Trim(), out var extraFiles))
        {
            foreach (var kv in extraFiles)
            {
                var idx = fileMap.FindIndex(f => string.Equals(f.Name, kv.Key, StringComparison.OrdinalIgnoreCase));
                if (idx >= 0) fileMap[idx] = (kv.Key, fileMap[idx].FilePath, kv.Value, false);
                else fileMap.Add((kv.Key, null, kv.Value, false));
            }
        }

        if (fileMap.Count == 0)
            throw new InvalidOperationException($"No C# source files found for input: {sourceOrPath}");

        fileMap.Add(("__ImplicitGlobalUsings.g.cs", null, ImplicitGlobalUsingsSource, true));

        var parseOptions = CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Preview);
        var compilationOptions = new CSharpCompilationOptions(
            OutputKind.DynamicallyLinkedLibrary,
            allowUnsafe: true,
            nullableContextOptions: NullableContextOptions.Enable,
            concurrentBuild: true);

        var workspace = new AdhocWorkspace();
        var projectId = ProjectId.CreateNewId(debugName: projectName);
        workspace.AddProject(ProjectInfo.Create(
            projectId,
            VersionStamp.Create(),
            projectName,
            projectName,
            LanguageNames.CSharp,
            parseOptions: parseOptions,
            compilationOptions: compilationOptions,
            metadataReferences: DefaultReferences));

        var docIds = new List<(DocumentId Id, string Name, string? FilePath, string Source, bool IsSynthetic)>(fileMap.Count);
        foreach (var (name, filePath, src, isSynthetic) in fileMap)
        {
            var docId = DocumentId.CreateNewId(projectId, debugName: name);
            var loader = TextLoader.From(TextAndVersion.Create(SourceText.From(src), VersionStamp.Create(), filePath ?? name));
            workspace.AddDocument(DocumentInfo.Create(docId, name, filePath: filePath ?? name, loader: loader));
            docIds.Add((docId, name, filePath, src, isSynthetic));
        }

        var solution = workspace.CurrentSolution;
        var project = solution.GetProject(projectId)!;
        var compilation = (CSharpCompilation)project.GetCompilationAsync().GetAwaiter().GetResult()!;

        var entries = docIds.Select(d =>
        {
            var doc = project.GetDocument(d.Id)!;
            var tree = doc.GetSyntaxTreeAsync().GetAwaiter().GetResult()!;
            return new DocumentEntry(d.Id, d.Name, d.FilePath, d.Source, tree, compilation.GetSemanticModel(tree), d.IsSynthetic);
        }).ToList();

        return new WorkspaceContext(workspace, solution, project, compilation, entries, isFromDisk, rootPath);
    }

    private static bool TryParseSourceDictionary(string json, out Dictionary<string, string> dict)
    {
        dict = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        try
        {
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.ValueKind != JsonValueKind.Object) return false;
            foreach (var prop in doc.RootElement.EnumerateObject())
            {
                if (prop.Value.ValueKind != JsonValueKind.String) return false;
                dict[prop.Name] = prop.Value.GetString() ?? "";
            }
            return dict.Count > 0;
        }
        catch { return false; }
    }

    private static bool LooksLikeDiskPath(string input, out string fullPath)
    {
        fullPath = "";
        if (input.Contains('\n') || input.Contains('\r') || input.Contains(';') || input.Contains('{'))
            return false;
        try
        {
            if (File.Exists(input) || Directory.Exists(input))
            {
                fullPath = Path.GetFullPath(input);
                return true;
            }
        }
        catch { }
        return false;
    }

    private static string? FindEnclosingProjectDirectory(string startDir)
    {
        for (var dir = new DirectoryInfo(startDir); dir is not null; dir = dir.Parent)
        {
            if (dir.GetFiles("*.csproj").Length > 0 || dir.GetFiles("*.sln").Length > 0 || dir.GetFiles("*.slnx").Length > 0)
                return dir.FullName;
        }
        return null;
    }

    private static void LoadFromCsproj(
        string csprojPath,
        string rootDir,
        List<(string Name, string? FilePath, string Source, bool IsSynthetic)> fileMap,
        HashSet<string>? visitedProjects = null)
    {
        visitedProjects ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var fullCsproj = Path.GetFullPath(csprojPath);
        if (!visitedProjects.Add(fullCsproj) || !File.Exists(fullCsproj))
            return;

        var projDir = Path.GetDirectoryName(fullCsproj)!;
        foreach (var csFile in EnumerateCSharpFiles(projDir))
        {
            if (!fileMap.Any(f => string.Equals(f.FilePath, csFile, StringComparison.OrdinalIgnoreCase)))
                fileMap.Add((Path.GetRelativePath(rootDir, csFile).Replace('\\', '/'), csFile, File.ReadAllText(csFile), false));
        }

        try
        {
            var doc = XDocument.Load(fullCsproj);
            var ns = doc.Root?.Name.Namespace ?? XNamespace.None;
            foreach (var pr in doc.Descendants(ns + "ProjectReference"))
            {
                var include = pr.Attribute("Include")?.Value;
                if (!string.IsNullOrWhiteSpace(include))
                    LoadFromCsproj(Path.GetFullPath(Path.Combine(projDir, include.Replace('\\', Path.DirectorySeparatorChar))), rootDir, fileMap, visitedProjects);
            }
        }
        catch { }
    }

    private static void LoadFromSolutionFile(
        string slnPath,
        string rootDir,
        List<(string Name, string? FilePath, string Source, bool IsSynthetic)> fileMap)
    {
        var visited = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (Path.GetExtension(slnPath).Equals(".slnx", StringComparison.OrdinalIgnoreCase))
        {
            try
            {
                var doc = XDocument.Load(slnPath);
                foreach (var projEl in doc.Descendants("Project"))
                {
                    var p = projEl.Attribute("Path")?.Value;
                    if (!string.IsNullOrWhiteSpace(p))
                        LoadFromCsproj(Path.GetFullPath(Path.Combine(rootDir, p.Replace('\\', Path.DirectorySeparatorChar))), rootDir, fileMap, visited);
                }
            }
            catch { }
        }
        else
        {
            foreach (var line in File.ReadLines(slnPath))
            {
                var m = Regex.Match(line, @"Project\(""[^""]+""\)\s*=\s*""[^""]+"",\s*""([^""]+\.csproj)""");
                if (m.Success)
                    LoadFromCsproj(Path.GetFullPath(Path.Combine(rootDir, m.Groups[1].Value.Replace('\\', Path.DirectorySeparatorChar))), rootDir, fileMap, visited);
            }
        }

        if (fileMap.Count == 0)
        {
            foreach (var csFile in EnumerateCSharpFiles(rootDir))
                fileMap.Add((Path.GetRelativePath(rootDir, csFile).Replace('\\', '/'), csFile, File.ReadAllText(csFile), false));
        }
    }

    public static IEnumerable<string> EnumerateCSharpFiles(string directory)
    {
        var excludedDirs = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "bin", "obj", ".git", ".vs", ".idea", "node_modules", "Unselected files"
        };

        var stack = new Stack<string>([directory]);
        var results = new List<string>();
        while (stack.Count > 0)
        {
            var current = stack.Pop();
            try
            {
                foreach (var file in Directory.GetFiles(current, "*.cs"))
                    results.Add(Path.GetFullPath(file));

                foreach (var subDir in Directory.GetDirectories(current))
                {
                    var name = Path.GetFileName(subDir);
                    if (!excludedDirs.Contains(name) && !name.StartsWith('.'))
                        stack.Push(subDir);
                }
            }
            catch { }
        }

        results.Sort(StringComparer.OrdinalIgnoreCase);
        return results;
    }

    public static ResolvedTarget ResolveTarget(WorkspaceContext ctx, string locationOrSymbol)
    {
        if (string.IsNullOrWhiteSpace(locationOrSymbol))
            throw new ArgumentException("locationOrSymbol cannot be empty", nameof(locationOrSymbol));

        var q = locationOrSymbol.Trim();

        if (q.StartsWith('@') && int.TryParse(q[1..], out var rawOffset))
            return ResolveAtOffset(ctx.PrimaryDocument, rawOffset);

        var colonParts = q.Split(':');
        if (colonParts.Length is 2 or 3 && colonParts[0].EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
        {
            var doc = ctx.FindDocument(colonParts[0])
                ?? throw new ArgumentException($"Document '{colonParts[0]}' not found in workspace.");
            if (int.TryParse(colonParts[1], out var fLine))
            {
                var fCol = colonParts.Length == 3 && int.TryParse(colonParts[2], out var c) ? c : 1;
                return ResolveAtLineColumn(doc, fLine, fCol);
            }
        }

        if (colonParts.Length == 2 && int.TryParse(colonParts[0], out var lineNum) && int.TryParse(colonParts[1], out var colNum))
            return ResolveAtLineColumn(ctx.PrimaryDocument, lineNum, colNum);

        var symbolTarget = TryResolveBySymbolName(ctx, q);
        if (symbolTarget is not null)
            return symbolTarget;

        if (q.StartsWith("L", StringComparison.OrdinalIgnoreCase) && int.TryParse(q[1..], out var explicitLine))
            return ResolveAtLineColumn(ctx.PrimaryDocument, explicitLine, 1);

        if (int.TryParse(q, out var num) && num >= 0 && num <= ctx.PrimaryDocument.Source.Length)
            return ResolveAtOffset(ctx.PrimaryDocument, num);

        throw new ArgumentException(
            $"Could not resolve symbol or location '{locationOrSymbol}'. " +
            "Use a symbol name (e.g. 'ClassName.MethodName' or 'MethodName'), 'line:col' (1-based), 'File.cs:line:col', or '@offset'.");
    }

    public static ResolvedTarget ResolveAtLineColumn(DocumentEntry doc, int line1Based, int column1Based)
    {
        var text = doc.Tree.GetText();
        var clampedLine = Math.Clamp(line1Based - 1, 0, Math.Max(0, text.Lines.Count - 1));
        var textLine = text.Lines[clampedLine];
        var clampedCol = Math.Clamp(column1Based - 1, 0, Math.Max(0, textLine.Span.Length));
        var position = textLine.Start + clampedCol;

        if (column1Based <= 1)
        {
            while (position < textLine.End && char.IsWhiteSpace(doc.Source[position]))
                position++;
        }

        return ResolveAtOffset(doc, position);
    }

    public static ResolvedTarget ResolveAtOffset(DocumentEntry doc, int offset)
    {
        if (offset < 0 || offset > doc.Source.Length)
            throw new ArgumentException($"Offset {offset} is out of bounds [0..{doc.Source.Length}].", nameof(offset));

        var root = doc.Tree.GetRoot();
        var node = root.FindToken(offset).Parent ?? root;
        var symbol = doc.Model.ResolveSymbol(node);

        if (symbol is null)
        {
            for (var cur = node.Parent; cur is not null; cur = cur.Parent)
            {
                symbol = doc.Model.ResolveSymbol(cur);
                if (symbol is not null) { node = cur; break; }
            }
        }

        var lr = doc.Tree.LineRange(new TextSpan(offset, 0));
        return new ResolvedTarget(doc, node, symbol, offset, lr.StartLine, lr.StartColumn);
    }

    public static ResolvedTarget? TryResolveBySymbolName(WorkspaceContext ctx, string symbolQuery)
    {
        string cleanQuery = symbolQuery.Trim();
        string? paramFilter = null;
        var parenIdx = cleanQuery.IndexOf('(');
        if (parenIdx > 0 && cleanQuery.EndsWith(')'))
        {
            paramFilter = cleanQuery[(parenIdx + 1)..^1].Trim();
            cleanQuery = cleanQuery[..parenIdx].Trim();
        }

        var candidates = new List<(DocumentEntry Doc, SyntaxNode Node, ISymbol Symbol, int Score)>();

        foreach (var doc in ctx.UserDocuments)
        {
            foreach (var node in doc.Tree.GetRoot().DescendantNodes())
            {
                if (node is not (BaseTypeDeclarationSyntax or MethodDeclarationSyntax or PropertyDeclarationSyntax
                    or EventDeclarationSyntax or ConstructorDeclarationSyntax or EnumMemberDeclarationSyntax
                    or DelegateDeclarationSyntax or VariableDeclaratorSyntax or ParameterSyntax or LocalFunctionStatementSyntax))
                {
                    continue;
                }

                var sym = doc.Model.GetDeclaredSymbol(node);
                if (sym is null) continue;

                int score = MatchSymbolScore(sym, cleanQuery, paramFilter);
                if (score > 0) candidates.Add((doc, node, sym, score));
            }
        }

        if (candidates.Count == 0)
        {
            var leafName = cleanQuery.Split('.').Last();
            foreach (var doc in ctx.UserDocuments)
            {
                foreach (var idNode in doc.Tree.GetRoot().DescendantNodes().OfType<IdentifierNameSyntax>())
                {
                    if (!string.Equals(idNode.Identifier.ValueText, leafName, StringComparison.OrdinalIgnoreCase))
                        continue;
                    var sym = doc.Model.ResolveSymbol(idNode);
                    if (sym is null) continue;
                    int score = MatchSymbolScore(sym, cleanQuery, paramFilter);
                    if (score > 0) candidates.Add((doc, idNode, sym, score - 5));
                }
            }
        }

        if (candidates.Count == 0) return null;

        var best = candidates.OrderByDescending(c => c.Score).First();
        var lr = best.Node.LineRange();
        return new ResolvedTarget(best.Doc, best.Node, best.Symbol, best.Node.SpanStart, lr.StartLine, lr.StartColumn);
    }

    private static int MatchSymbolScore(ISymbol symbol, string query, string? paramFilter)
    {
        var fullDisplay = symbol.FullDisplay();
        var fullNoParams = fullDisplay.Contains('(') ? fullDisplay[..fullDisplay.IndexOf('(')] : fullDisplay;
        var typeAndName = symbol.ContainingType is not null ? $"{symbol.ContainingType.Name}.{symbol.Name}" : symbol.Name;

        int score = 0;
        if (string.Equals(fullNoParams, query, StringComparison.Ordinal)) score = 100;
        else if (string.Equals(typeAndName, query, StringComparison.Ordinal)) score = 95;
        else if (string.Equals(symbol.Name, query, StringComparison.Ordinal)) score = 90;
        else if (string.Equals(fullNoParams, query, StringComparison.OrdinalIgnoreCase)) score = 85;
        else if (string.Equals(typeAndName, query, StringComparison.OrdinalIgnoreCase)) score = 80;
        else if (string.Equals(symbol.Name, query, StringComparison.OrdinalIgnoreCase)) score = 75;
        else if (fullNoParams.EndsWith("." + query, StringComparison.OrdinalIgnoreCase)) score = 70;

        if (score == 0) return 0;

        if (paramFilter is not null && symbol is IMethodSymbol methodSym)
        {
            var filterParts = paramFilter.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            if (filterParts.Length != methodSym.Parameters.Length) return 0;

            for (int i = 0; i < filterParts.Length; i++)
            {
                var pType = methodSym.Parameters[i].Type.MinDisplay();
                var pName = methodSym.Parameters[i].Name;
                if (!pType.Contains(filterParts[i], StringComparison.OrdinalIgnoreCase) &&
                    !string.Equals(pName, filterParts[i], StringComparison.OrdinalIgnoreCase))
                {
                    return 0;
                }
            }
            score += 10;
        }

        return score;
    }

    public static string FormatSyntaxNode(SyntaxNode node) => node.FormatWithRoslyn();

    public static DiffSummary BuildDiffSummary(string oldText, string newText) =>
        RoslynHelpers.BuildDiff(oldText, newText);

    public static object FormatLocation(Location loc)
    {
        if (!loc.IsInSource || loc.SourceTree is null)
            return new { inSource = false, metadata = loc.MetadataModule?.Name };

        var lr = loc.SourceTree.LineRange(loc.SourceSpan);
        var text = loc.SourceTree.GetText();
        var lineText = lr.StartLine - 1 >= 0 && lr.StartLine - 1 < text.Lines.Count
            ? text.Lines[lr.StartLine - 1].ToString().Trim()
            : "";

        return new SourceLocationInfo(
            File: string.IsNullOrWhiteSpace(loc.SourceTree.FilePath) ? "Source.cs" : Path.GetFileName(loc.SourceTree.FilePath),
            FullPath: loc.SourceTree.FilePath,
            StartLine: lr.StartLine,
            StartColumn: lr.StartColumn,
            EndLine: lr.EndLine,
            EndColumn: lr.EndColumn,
            SpanStart: loc.SourceSpan.Start,
            SpanLength: loc.SourceSpan.Length,
            LineText: lineText);
    }

    public static (int Errors, int Warnings, DiagnosticItem[] Diagnostics) GetCompilationDiagnostics(string source, WorkspaceContext? existingCtx = null)
    {
        var tree = CSharpSyntaxTree.ParseText(source, CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Preview), "Modified.cs");
        var trees = new List<SyntaxTree> { tree };

        if (existingCtx is not null)
        {
            foreach (var d in existingCtx.Documents)
            {
                if (d.Id != existingCtx.PrimaryDocument.Id)
                    trees.Add(d.Tree);
            }
        }
        else
        {
            trees.Add(CSharpSyntaxTree.ParseText(ImplicitGlobalUsingsSource, path: "__ImplicitGlobalUsings.g.cs"));
        }

        var comp = CSharpCompilation.Create(
            "ValidationCompilation",
            trees,
            DefaultReferences,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, allowUnsafe: true, nullableContextOptions: NullableContextOptions.Enable));

        var diags = comp.GetDiagnostics()
            .Where(d => d.Location.SourceTree == tree && d.Severity >= DiagnosticSeverity.Warning)
            .OrderByDescending(d => d.Severity)
            .ThenBy(d => d.Location.SourceSpan.Start)
            .ToArray();

        int errors = diags.Count(d => d.Severity == DiagnosticSeverity.Error);
        int warnings = diags.Count(d => d.Severity == DiagnosticSeverity.Warning);

        var formatted = diags.Take(50).Select(d =>
        {
            var lr = tree.LineRange(d.Location.SourceSpan);
            return new DiagnosticItem(d.Id, d.Severity.ToString(), d.GetMessage(), lr.StartLine, lr.StartColumn);
        }).ToArray();

        return (errors, warnings, formatted);
    }

    /// <summary>
    /// Shared post-processor for AST mutations: formats the new root, optionally persists to disk,
    /// computes compilation diagnostics before/after, and computes the inline diff.
    /// </summary>
    public static MutationOutcome FinalizeMutation(
        WorkspaceContext ctx,
        DocumentEntry doc,
        SyntaxNode newRoot,
        bool writeToDisk)
    {
        var formattedSource = newRoot.FormatWithRoslyn();
        bool saved = false;
        if (writeToDisk && !string.IsNullOrWhiteSpace(doc.FilePath) && File.Exists(doc.FilePath))
        {
            File.WriteAllText(doc.FilePath, formattedSource);
            saved = true;
        }

        int errorsBefore = doc.Model.GetDiagnostics().Count(d => d.Severity == DiagnosticSeverity.Error);
        var (errorsAfter, warningsAfter, diags) = GetCompilationDiagnostics(formattedSource, ctx);
        var diff = RoslynHelpers.BuildDiff(doc.Source, formattedSource);

        return new MutationOutcome(doc.Name, formattedSource, saved, errorsBefore, errorsAfter, warningsAfter, diags, diff);
    }

    public static string ExtractXmlSummary(ISymbol symbol) => symbol.GetXmlSummary();

    public static string[] GetSymbolModifiers(ISymbol symbol) => symbol.GetModifiers();
}
